add duration for the folders
dimkanovikov/starc pull request #20
Opened 2021-02-01 18:45 UTC by littlehobbit

2021-02-02 08:39 UTC, dimkanovikov requested changes
Отлично! Но надо докрутить :)

2021-02-02 08:39 UTC, dimkanovikov commented on src/core/management_layer/plugins/screenplay_text_structure/ui/screenplay_text_structure_delegate.cpp
> +    const qreal folderNameWidth = folderDurationRect.left() - folderNameLeft - Ui::DesignSystem::treeOneLineItem().margins().right();
тут вместо `margins` стоит использовать `spacing`, т.к. теперь уже нужен отступ между элементами внутри

2021-02-02 08:39 UTC, dimkanovikov commented on src/core/management_layer/plugins/screenplay_text_structure/ui/screenplay_text_structure_delegate.cpp
> +    auto sceneDurationRect = paintDuration(_painter, _option, _index);
`const`

2021-02-02 08:39 UTC, dimkanovikov commented on src/core/management_layer/plugins/screenplay_text_structure/ui/screenplay_text_structure_delegate.cpp
> +    auto folderDurationRect = paintDuration(_painter, _option, _index);
`const`

2021-02-02 08:39 UTC, dimkanovikov commented on src/core/management_layer/plugins/screenplay_text_structure/ui/screenplay_text_structure_delegate.cpp
> +    const QRectF backgroundRect = _option.rect;
нужно опустить его туда, где он начинает использоваться

2021-02-02 08:39 UTC, dimkanovikov commented on src/core/management_layer/plugins/screenplay_text_structure/ui/screenplay_text_structure_delegate.cpp
> +    QRectF paintDuration(QPainter *_painter, const QStyleOptionViewItem& _option, const QModelIndex& _index) const;
указатели и ссылки пишем у типа переменной, а не у названия

2021-02-02 08:39 UTC, dimkanovikov commented on src/core/management_layer/plugins/screenplay_text_structure/ui/screenplay_text_structure_delegate.cpp
> +QRectF ScreenplayTextStructureDelegate::Implementation::paintDuration(QPainter *_painter, const QStyleOptionViewItem& _option, const QModelIndex &_index) const
тут аналогично со ссылками и указателем

2021-02-02 08:39 UTC, dimkanovikov commented on src/core/management_layer/plugins/screenplay_text_structure/ui/screenplay_text_structure_delegate.cpp
> +    auto textColor = _option.palette.color(QPalette::Text);
`const` или сразу в задание пера рисовальщику перенести, т.к. больше эта переменная тут нигде не используется

2021-02-02 08:39 UTC, dimkanovikov commented on src/core/management_layer/plugins/screenplay_text_structure/ui/screenplay_text_structure_delegate.cpp
> +    const QRectF itemDurationRect(QPointF(backgroundRect.right() - itemDurationWidth - Ui::DesignSystem::treeOneLineItem().margins().right(),
предлагаю викинуть `item` из назаваний элементов, вроде никакой дополнительной смысловой пользы оно не несёт

2021-02-02 10:54 UTC, dimkanovikov commented on src/core/management_layer/plugins/screenplay_text_structure/ui/screenplay_text_structure_delegate.cpp
> +    const QRectF backgroundRect = _option.rect;
тут имел в виду не `namespace` (с ним как раз всё ок, ты вначале метода как бы говоришь, что тут эту область видимости будем использовать), а `backgroundRect`

2021-02-04 08:34 UTC, littlehobbit commented on src/core/management_layer/plugins/screenplay_text_structure/ui/screenplay_text_structure_delegate.cpp
> +    const QRectF backgroundRect = _option.rect;
исправлено с:

2021-02-04 09:42 UTC, merged