fix checkbox's layout for RTL langueges
dimkanovikov/starc pull request #24
Opened 2021-02-05 09:38 UTC by littlehobbit

2021-02-05 10:08 UTC, dimkanovikov requested changes

2021-02-05 10:08 UTC, dimkanovikov commented on src/corelib/ui/widgets/check_box/check_box.cpp
> +                - Ui::DesignSystem::checkBox().spacing();
Тут предлагаю  немного докрутить - перечислять параметры так, чтобы в будущем при чтении кода было понятно, что и как тут вычитается, типа:

ширина - отступ с левого края - расстояние между текстом и иконкой - ширина иконки - отступ с правого края

2021-02-05 10:08 UTC, dimkanovikov commented on src/corelib/ui/widgets/check_box/check_box.cpp
> +        iconRect.setRect(textRectX + textWidth
тут вот пустые строки - они что отделяют? обычно пустоты добавляют, когда хотят разделить какие-то локические блоки, тут кажется просто формирование переменных идёт, не очень понимаю их целесообразность...

2021-02-07 09:39 UTC, littlehobbit commented on src/corelib/ui/widgets/check_box/check_box.cpp
> +                - Ui::DesignSystem::checkBox().spacing();
Исправлено с:

2021-02-07 09:40 UTC, littlehobbit commented on src/corelib/ui/widgets/check_box/check_box.cpp
> +        iconRect.setRect(textRectX + textWidth
Исправлено с:

2021-02-07 09:51 UTC, merged