fix RTL layout for buttons
dimkanovikov/starc pull request #26
Opened 2021-02-08 10:53 UTC by littlehobbit

2021-02-08 11:31 UTC, dimkanovikov requested changes

2021-02-08 11:31 UTC, dimkanovikov commented on src/corelib/ui/widgets/button/button.cpp
> +            iconX = buttonInnerRect.x()
тут в обоих условиях плюсуется `buttonInnerRect.x()`, предлагаю сразу им и инициилизировать `iconX`

2021-02-08 11:31 UTC, dimkanovikov commented on src/corelib/ui/widgets/button/button.cpp
> +        }
тут предлагаю аналогично общую часть вынести, а после изменить условие, чтобы оно в одной общей ветке считало для `isContined == true`, а в другой добавляло дополнительное значение, если нужно

2021-02-08 20:11 UTC, littlehobbit commented on src/corelib/ui/widgets/button/button.cpp
> +        }
Вынесено

2021-02-08 20:11 UTC, littlehobbit commented on src/corelib/ui/widgets/button/button.cpp
> +            iconX = buttonInnerRect.x()
Инициализировано :D

2021-02-09 03:29 UTC, dimkanovikov requested changes

2021-02-09 03:29 UTC, dimkanovikov commented on src/corelib/ui/widgets/button/button.cpp
> +            iconX += (d->isContained
тут скобка окружающая больше не нужна

2021-02-09 03:29 UTC, dimkanovikov commented on src/corelib/ui/widgets/button/button.cpp
> +            iconX += (d->isContained
тут тоже

2021-02-09 03:29 UTC, dimkanovikov commented on src/corelib/ui/widgets/button/button.cpp
> +            textX += (isLeftToRight())
ну и тут тоже

2021-02-09 08:31 UTC, littlehobbit commented on src/corelib/ui/widgets/button/button.cpp
> +            iconX += (d->isContained
Сделано с:

2021-02-09 08:31 UTC, littlehobbit commented on src/corelib/ui/widgets/button/button.cpp
> +            iconX += (d->isContained
Сделано с:

2021-02-09 08:32 UTC, littlehobbit commented on src/corelib/ui/widgets/button/button.cpp
> +            textX += (isLeftToRight())
Сделано с:

2021-02-09 09:26 UTC, merged