add focus, hower, rtl support
dimkanovikov/starc pull request #30
Opened 2021-05-15 15:43 UTC by marshevms

2021-05-15 15:45 UTC, marshevms commented on src/corelib/ui/widgets/slider/slider.cpp
>  void Slider::Implementation::animateClick()
Для чего сдесь setCurrentTime(0) ?

2021-05-15 15:46 UTC, marshevms commented on src/corelib/ui/widgets/slider/slider.cpp
> +}
в buttons возвращается Widget::keyPressEvent(_event) для чего? Тут тоже нужно?

2021-05-15 15:48 UTC, marshevms commented on src/corelib/ui/widgets/slider/slider.cpp
> +    const QRectF leftTrackRect(QPointF((isRightToLeft()? contentsRect().width() + contentsMargins().left() : contentsMargins().left()),
Тут я что-то так и не допер почему нужно еще **contentsMargins().left()** прибавлять, без него всег съезжает

2021-05-15 19:35 UTC, dimkanovikov requested changes

2021-05-15 19:35 UTC, dimkanovikov commented on src/corelib/ui/widgets/slider/slider.cpp
> +    void animateHoverOut();
А почему ховер решил анимированным сделать? обычно его как раз не делают анимированным, чтобы не было эффекта следа от мыши, при перемещении курсора между разными элементами управления

2021-05-15 19:35 UTC, dimkanovikov commented on src/corelib/ui/widgets/slider/slider.cpp
>  void Slider::Implementation::animateClick()
потому что, когда запустится анимация радиуса, если не сбросить прозрачность, то до момента запуска анимации прозрачности может проскачить кадр с финальным значением с предыдущей анимации

2021-05-15 19:35 UTC, dimkanovikov commented on src/corelib/ui/widgets/slider/slider.cpp
> +    const QRectF leftTrackRect(QPointF((isRightToLeft()? contentsRect().width() + contentsMargins().left() : contentsMargins().left()),
:) это потому что `contentsRect` возвращает область за вычетом `contentsMargins`, соответственно если левый и правый отступы заданы, то ширина ректа будет меньше на их сумму

2021-05-15 19:35 UTC, dimkanovikov commented on src/corelib/ui/widgets/slider/slider.cpp
> +                               QSizeF((isRightToLeft()? -1 : 1) * leftTrackWidth, Ui::DesignSystem::slider().trackHeight()));
тут предлагаю не брать отрицательную ширину, а добавить это смещение в координату Х

2021-05-15 19:35 UTC, dimkanovikov commented on src/corelib/ui/widgets/slider/slider.cpp
> +                                QSizeF((isRightToLeft()? -1 : 1) * (trackWidth - leftTrackWidth), leftTrackRect.height()));
тут соответственно тоже лучше сдвинуть координату, а размер оставить

2021-05-15 19:35 UTC, dimkanovikov commented on src/corelib/ui/widgets/slider/slider.cpp
> +            painter.setOpacity(d->howerOpacityAnimation.endValue().toReal() + 0.1);
прозрачности у нас лежат в дизайн системе, там есть значения и для ховера и для фокуса, смотри `Ui::DesignSystem::hoverBackgroundOpacity()` etc

2021-05-15 19:35 UTC, dimkanovikov commented on src/corelib/ui/widgets/slider/slider.cpp
> +    clearFocus();
А зачем тут сбрасывать фокус?

2021-05-15 19:35 UTC, dimkanovikov commented on src/corelib/ui/widgets/slider/slider.cpp
> +}
это я фигню понаписал, по-хорошему не нужно этого. Спасибо, уберу)

2021-05-15 19:35 UTC, dimkanovikov commented on src/corelib/ui/widgets/slider/slider.h
> +    int calcValue(int _mousePosition, int _trackWidth);
предлагаю это в пимпл перенести

2021-05-15 19:48 UTC, marshevms commented on src/corelib/ui/widgets/slider/slider.cpp
> +    void animateHoverOut();
Чет посмотрел примеры из стайл гайда и там вроде как есть или у меня глаз замылился?

2021-05-15 19:50 UTC, marshevms commented on src/corelib/ui/widgets/slider/slider.cpp
> +    clearFocus();
Мне показалось как-то странно оставлять фокус, если мы изменили значение, но если должен фокус остаться, то оставлю

2021-05-16 03:34 UTC, dimkanovikov commented on src/corelib/ui/widgets/slider/slider.cpp
> +    void animateHoverOut();
А где ты смотрел, кинь ссылку пожалуйста.

2021-05-16 03:35 UTC, dimkanovikov commented on src/corelib/ui/widgets/slider/slider.cpp
> +    clearFocus();
должен оставаться, ты же можешь зажать мышь и двигать, потом отпустить, а потом решить кнопками подвигать ползунок

2021-05-16 03:36 UTC, dimkanovikov commented on src/corelib/ui/widgets/slider/slider.cpp
> +    const QRectF leftTrackRect(QPointF((isRightToLeft()? contentsRect().width() + contentsMargins().left() : contentsMargins().left()),
тут и далее пробел перед условным оператором (?)

2021-05-16 03:41 UTC, dimkanovikov commented on src/corelib/ui/widgets/slider/slider.cpp
> +        if (underMouse() && !hasFocus()){
style: пробел перед фигурной скобкой

2021-05-16 03:41 UTC, dimkanovikov commented on src/corelib/ui/widgets/slider/slider.cpp
> +                 ||d->howerRadiusAnimation.state() == QVariantAnimation::Running)){
style: пробел перед ||| и перед {

2021-05-16 03:41 UTC, dimkanovikov commented on src/corelib/ui/widgets/slider/slider.cpp
> +
style: лишняя пустая строка

2021-05-16 03:41 UTC, dimkanovikov commented on src/corelib/ui/widgets/slider/slider.cpp
> +                   ||d->howerRadiusAnimation.state() == QVariantAnimation::Running){
style: аналогично с пробелами

2021-05-16 03:41 UTC, dimkanovikov commented on src/corelib/ui/widgets/slider/slider.cpp
> +        }else if (hasFocus()){
style: опять пробелы :) после } и перед {

2021-05-16 03:41 UTC, dimkanovikov commented on src/corelib/ui/widgets/slider/slider.cpp
> +    if (hasFocus()) return;
style: такие улсовия должны быть записаны в фигурных скобках на отдельной строке
```
if (hasFocus()) {
    return;
}
````

2021-05-16 03:41 UTC, dimkanovikov commented on src/corelib/ui/widgets/slider/slider.h
> +    void leaveEvent(QEvent *_event) override;
style: тут нужен коммент

2021-05-16 08:51 UTC, marshevms commented on src/corelib/ui/widgets/slider/slider.cpp
> +    void animateHoverOut();
https://material.io/components/sliders#continuous-sliders

2021-05-16 09:13 UTC, dimkanovikov commented on src/corelib/ui/widgets/slider/slider.cpp
> +    void animateHoverOut();
Так это там клик анимируется, а ховер там не показан. Предлагаю сделать его без анимации.

2021-05-16 10:40 UTC, marshevms commented on src/corelib/ui/widgets/slider/slider.cpp
> +    void animateHoverOut();
Убрал

2021-05-16 10:41 UTC, marshevms commented on src/corelib/ui/widgets/slider/slider.cpp
> +                               QSizeF((isRightToLeft()? -1 : 1) * leftTrackWidth, Ui::DesignSystem::slider().trackHeight()));
Добавил смещение

2021-05-16 10:41 UTC, marshevms commented on src/corelib/ui/widgets/slider/slider.cpp
> +            painter.setOpacity(d->howerOpacityAnimation.endValue().toReal() + 0.1);
ага, исправил

2021-05-16 10:41 UTC, marshevms commented on src/corelib/ui/widgets/slider/slider.cpp
> +    clearFocus();
убрал

2021-05-16 10:42 UTC, marshevms commented on src/corelib/ui/widgets/slider/slider.h
> +    int calcValue(int _mousePosition, int _trackWidth);
перенес

2021-05-16 10:57 UTC, dimkanovikov commented on src/corelib/ui/widgets/slider/slider.cpp
> +    const int margin = contentsRect().left();
предлагаю назвать `leftMargin` и опустить в то место, где оно используется

2021-05-16 10:57 UTC, dimkanovikov commented on src/corelib/ui/widgets/slider/slider.h
> -    void leaveEvent(QEvent *_event) override;
А ховер разве будет работать, если виджет не просить обновиться?

2021-05-16 11:00 UTC, marshevms commented on src/corelib/ui/widgets/slider/slider.h
> -    void leaveEvent(QEvent *_event) override;
да, [https://github.com/dimkanovikov/starc/pull/30/files#diff-b2f2b7e2e606ffc5749e5afc8bd1ed3e0998262a11fdff5cd3432bd3f5504f93R71](просит update)

2021-05-16 11:12 UTC, merged