Settings slider update
dimkanovikov/starc pull request #34
Opened 2021-05-30 11:31 UTC by KalinaVitaly

2021-05-30 12:32 UTC, dimkanovikov requested changes

2021-05-30 12:32 UTC, dimkanovikov commented on src/corelib/ui/widgets/slider/slider.h
> +    void setStartPosition(int _value);
Предлагаю назвать это позицией по-умолчанию, т.к. она не всегда будет стартовой

Плюс нужен способ как-то убрать эту возможность, т.е. если мне на слайдере ненужно дефолтное положение. Предлаагю сделать это через `std::optional`

2021-05-30 12:32 UTC, dimkanovikov commented on src/corelib/ui/widgets/slider/slider.cpp
> +#include <QDebug>
Это ещё нужно?

2021-05-30 12:32 UTC, dimkanovikov commented on src/corelib/ui/widgets/slider/slider.cpp
> +    int eps = 25;
по-умолчанию предлагаю делать позицию незаданной

eps - совершенно неговорящее название, можно что-нибудь типа `defaultPositionDelta`

2021-05-30 12:32 UTC, dimkanovikov commented on src/corelib/ui/widgets/slider/slider.cpp
> +    }
этот блок не понял зачем нужен?

2021-05-30 12:32 UTC, dimkanovikov commented on src/corelib/ui/widgets/slider/slider.cpp
> +    {
фигурная скобка на одной строке с `if`

2021-05-30 12:32 UTC, dimkanovikov commented on src/corelib/ui/widgets/slider/slider.cpp
> +    d->eps = _value * 0.05;
дельту нужно брать от всей ширины трека, а не от заданного значения (иначе оно будет меняться в зависимости от того, как близко или далеко от начала установлено дефолтное значение)

плюс, давай сделаем её 1%

2021-05-30 12:32 UTC, dimkanovikov commented on src/corelib/ui/widgets/slider/slider.cpp
> +    const qreal startTrackWidth = trackWidth * d->startPosition / d->maximum;
это нужно опустить к тому месту в коде, где переменная используется

2021-05-30 12:32 UTC, dimkanovikov commented on src/corelib/ui/widgets/slider/slider.cpp
> +    const qreal startPointRadious = 4;
размер надо взять из дизайн системы

2021-05-30 17:29 UTC, dimkanovikov commented on src/corelib/ui/widgets/slider/slider.h
> +    void setStartPosition(int _value);
А как сбросить?

2021-05-30 17:31 UTC, dimkanovikov commented on src/corelib/ui/widgets/slider/slider.cpp
> +    d->defaultPositionDelta = d->maximum * 0.01;
нужно учитывать изменение интервала значений

2021-05-30 17:32 UTC, dimkanovikov commented on src/corelib/ui/widgets/slider/slider.cpp
> +    std::optional<int> defaultPositionDelta = 25;
Почему тут optional и почему int?

2021-05-30 17:34 UTC, dimkanovikov commented on src/corelib/ui/widgets/slider/slider.cpp
> +            && _value <= d->defaultPosition.value() + d->defaultPositionDelta.value()) {
тут арифметические операции предлагаю взять в скобки, для улучшения восприятия и уменьшения вероятности ошибки при будущих правках

2021-06-04 15:27 UTC, KalinaVitaly commented on src/corelib/ui/widgets/slider/slider.h
> +    void setStartPosition(int _value);
добавил метод resetDefaultPosotion

2021-06-04 15:27 UTC, KalinaVitaly commented on src/corelib/ui/widgets/slider/slider.cpp
> +    d->defaultPositionDelta = d->maximum * 0.01;
Исправио

2021-06-04 15:28 UTC, KalinaVitaly commented on src/corelib/ui/widgets/slider/slider.cpp
> +    std::optional<int> defaultPositionDelta = 25;
изменил, теперь Delta  qreal и убрал option

2021-06-04 15:29 UTC, KalinaVitaly commented on src/corelib/ui/widgets/slider/slider.cpp
> +            && _value <= d->defaultPosition.value() + d->defaultPositionDelta.value()) {
исправил

2021-06-06 05:26 UTC, dimkanovikov commented on src/corelib/ui/widgets/slider/slider.cpp
> +    d->defaultPositionDelta = d->maximum * 0.01;
Не вижу где это исправлено... если изменю максимальную границу, дельта так и останется в текущем состоянии.

2021-06-06 05:27 UTC, dimkanovikov commented on src/corelib/ui/widgets/slider/slider.cpp
> +#include <optional>
тут предлагаю добавить пустую строку, обычно инклуды таким образом распределяем 

#внутренние классы

#классы Qt

#классы std

2021-06-06 05:28 UTC, dimkanovikov commented on src/corelib/ui/widgets/slider/slider.cpp
> +    std::optional<int> defaultPositionDelta = 25;
Супер, теперь ещё нужно убрать значения по-умолчанию, чтобы при желании его использовать нужно было самостоятельно это задать.

2021-06-06 05:29 UTC, dimkanovikov commented on src/corelib/ui/widgets/slider/slider.cpp
> +    {
codestyle: скобку на строку с условием

2021-06-06 05:30 UTC, dimkanovikov commented on src/corelib/ui/widgets/slider/slider.cpp
> +    {
И ещё, предлагаю тут в условии не просто `operatot()` использовать, а лучше `has_value`, так более наглядно, что происходит, при чтении кода

2021-06-06 05:32 UTC, dimkanovikov commented on src/corelib/ui/widgets/slider/slider.cpp
> +            && (_value <= d->defaultPosition.value() + d->defaultPositionDelta)) {
тут тоже самое с `has_value`, плюс предлагаю перегруппировать немного, вынести проверку на наличие значения из скобки с условием, что значение попадает в нужный интервал

2021-06-06 05:34 UTC, dimkanovikov commented on src/corelib/ui/widgets/slider/slider.h
> +     * @brief Сбросить позицию по-умолчанию слайдера
Предлагаю тут коммент в стиле "Отменить использование позиции по-умолчанию", а то воспринимается, что она так и будет использоваться, просто в некоем своём дефолтном состоянии

2021-06-08 08:30 UTC, KalinaVitaly commented on src/corelib/ui/widgets/slider/slider.cpp
> +#include <optional>
исправил

2021-06-08 08:31 UTC, KalinaVitaly commented on src/corelib/ui/widgets/slider/slider.cpp
> +    {
исправил

2021-06-08 08:32 UTC, KalinaVitaly commented on src/corelib/ui/widgets/slider/slider.h
> +     * @brief Сбросить позицию по-умолчанию слайдера
исправлено

2021-06-09 07:41 UTC, dimkanovikov commented on src/corelib/ui/widgets/slider/slider.cpp
> +    void setDefaultPositionDelta();
название метода не очень удачное - сеттер должен что-то устанавливать, а тут просто обновление или персчёт значения

2021-06-09 07:50 UTC, dimkanovikov commented on src/corelib/ui/widgets/slider/slider.cpp
> +    std::optional<int> defaultPositionDelta = 25;
Так, для дельты лучше всё таки какое-то значение оставить 0, или nan, т.к. неинициилизированная переменная типа POD - это всегда потенциальные проблемы.

2021-06-09 07:53 UTC, dimkanovikov commented on src/corelib/ui/widgets/slider/slider.cpp
> +            && (_value <= d->defaultPosition.value() + d->defaultPositionDelta)) {
Имел в виду что-то вот такое. 

```cpp
if (d->defaultPosition.has_value()
            && (_value >= d->defaultPosition.value() - d->defaultPositionDelta)
            && (_value <= d->defaultPosition.value() + d->defaultPositionDelta)) {
```

Причина этому, что операции на границе условий могут иметь не такой приоритет выполнения, как ты ожидаешь и тогда реальный порядок во время выполнения будет отличаться от того, который задумал автор.

2021-06-09 08:12 UTC, KalinaVitaly commented on src/corelib/ui/widgets/slider/slider.cpp
> +            && (_value <= d->defaultPosition.value() + d->defaultPositionDelta)) {
исправил

2021-06-09 08:14 UTC, KalinaVitaly commented on src/corelib/ui/widgets/slider/slider.cpp
> +    void setDefaultPositionDelta();
исправивил на calcDefaultPositionDelta

2021-06-09 08:15 UTC, KalinaVitaly commented on src/corelib/ui/widgets/slider/slider.cpp
> +    std::optional<int> defaultPositionDelta = 25;
поставил 0

2021-06-09 08:41 UTC, merged