WIP
dimkanovikov/starc pull request #42
Opened 2021-06-19 18:57 UTC by KalinaVitaly

2021-06-19 20:15 UTC, dimkanovikov requested changes

2021-06-19 20:15 UTC, dimkanovikov commented on src/corelib/ui/widgets/text_field/text_field.h
> +#include "../text_edit/base/base_text_edit.h"
тут надо подключить через <ui/widgets/...>

2021-06-19 20:15 UTC, dimkanovikov commented on src/corelib/ui/widgets/text_field/text_field.h
>  #include <QTextEdit>
это надо удалить

2021-06-19 20:15 UTC, dimkanovikov commented on src/corelib/ui/widgets/text_field/text_field.h
>  #include <corelib_global.h>
это тоже надо удалить

2021-06-20 09:31 UTC, KalinaVitaly commented on src/corelib/ui/widgets/text_field/text_field.h
> +#include "../text_edit/base/base_text_edit.h"
+

2021-06-20 09:31 UTC, KalinaVitaly commented on src/corelib/ui/widgets/text_field/text_field.h
>  #include <QTextEdit>
+

2021-06-20 09:32 UTC, KalinaVitaly commented on src/corelib/ui/widgets/text_field/text_field.h
>  #include <corelib_global.h>
+

2021-06-20 17:21 UTC, closed without merging