Добавлена блокировка файлов
dimkanovikov/starc pull request #44
Opened 2021-06-23 21:53 UTC by KalinaVitaly

2021-06-24 17:33 UTC, dimkanovikov requested changes

2021-06-24 17:33 UTC, dimkanovikov commented on src/core/management_layer/application_manager.cpp
> +    }
предлагаю этот блок перенести ниже, чтобы сперва производились защитные проверки, типа не передан ли пустой путь, или не пробует ли автор открыть уже открытый проект, а потом если всё ок, то сперва закрываем текущий проект и потом пробуем открыть заданный, предварительно проверяя блокировку

2021-06-24 17:33 UTC, dimkanovikov commented on src/core/management_layer/application_manager.cpp
> +            QObject::connect(dialog, &Dialog::finished, [dialog]() { dialog->hideDialog(); });
у нас есть более простой способ для однокнопочных диалогов `StandardDialog::information`

2021-06-24 17:33 UTC, dimkanovikov commented on src/core/management_layer/application_manager.cpp
> +        lockFile.unlock();
в доке пишут, что 

Calling unlock() without locking the file first, does nothing.

получается, что этот код нифига не делает)))

2021-06-24 21:45 UTC, KalinaVitaly commented on src/core/management_layer/application_manager.cpp
> +    }
+

2021-06-24 22:17 UTC, KalinaVitaly commented on src/core/management_layer/application_manager.cpp
> +            QObject::connect(dialog, &Dialog::finished, [dialog]() { dialog->hideDialog(); });
+

2021-06-25 08:22 UTC, dimkanovikov requested changes

2021-06-25 08:22 UTC, dimkanovikov commented on src/core/management_layer/application_manager.cpp
> +    QLockFile* lockFile = nullptr;
предлагаю таки на стеке его сделать

2021-06-25 08:22 UTC, dimkanovikov commented on src/core/management_layer/application_manager.cpp
> +    // qDebug() << lockFile->isLocked();
это нужно ещё?

2021-06-25 08:22 UTC, dimkanovikov commented on src/core/management_layer/application_manager.cpp
> +        if (lockFile->error() == QLockFile::LockFailedError) {
А если файл не удалось заблокировать по другой причине? предлагаю эту проверку опустить, если не удалось заблокировать, то не разрешаем работать с файлом в принципе

2021-06-25 08:22 UTC, dimkanovikov commented on src/core/management_layer/application_manager.cpp
> +                                        tr("This file is already open in anotherapplication"));
пробел потерял

2021-06-25 08:22 UTC, dimkanovikov commented on src/core/management_layer/application_manager.cpp
> +    }
этот блок давай перенесём ниже, под проверку о валидности текущего проекта

2021-06-25 13:10 UTC, KalinaVitaly commented on src/core/management_layer/application_manager.cpp
> +                                        tr("This file is already open in anotherapplication"));
+

2021-06-25 13:11 UTC, KalinaVitaly commented on src/core/management_layer/application_manager.cpp
> +    // qDebug() << lockFile->isLocked();
+

2021-06-25 13:11 UTC, KalinaVitaly commented on src/core/management_layer/application_manager.cpp
> +    QLockFile* lockFile = nullptr;
не получится)

2021-06-25 13:13 UTC, KalinaVitaly commented on src/core/management_layer/application_manager.cpp
> +        if (lockFile->error() == QLockFile::LockFailedError) {
+

2021-06-25 13:19 UTC, KalinaVitaly commented on src/core/management_layer/application_manager.cpp
> +    }
+

2021-06-25 14:26 UTC, dimkanovikov commented on src/core/management_layer/application_manager.cpp
> +    QLockFile* lockFile = nullptr;
тогда давай завернём в `QScopedPointer`

2021-06-25 14:27 UTC, dimkanovikov commented on src/core/management_layer/application_manager.cpp
> +    QLockFile* lockFile = nullptr;
и сделай пожалуйста ещё отступ от `q` и добавть комментарий

2021-06-25 14:28 UTC, dimkanovikov commented on src/core/management_layer/application_manager.cpp
> +        if (lockFile->isLocked()) {
тут предлагаю сделать два ассерта, ибо это файл блокирующий обязательно должен быть задан для проекта и он обязательно должен быть залочен

2021-06-30 21:31 UTC, KalinaVitaly commented on src/core/management_layer/application_manager.cpp
> +    QLockFile* lockFile = nullptr;
готово

2021-07-01 08:44 UTC, dimkanovikov commented on src/core/management_layer/application_manager.cpp
> +    if (!(lockFile.data())->tryLock()) {
тут скобки вокруг `lockFile` нужно убрать, и можно сделать без вызова `data()`

2021-07-01 08:44 UTC, dimkanovikov commented on src/core/management_layer/application_manager.cpp
> +    (lockFile.data())->setStaleLockTime(0);
тут аналогично

2021-07-01 08:44 UTC, dimkanovikov commented on src/core/management_layer/application_manager.cpp
> +        if (lockFile->isLocked()) {
Посмотрел - это не то, нужно просто вместо двух ифов сделать два асерта идущих подряд. И можно использовать Qt'овые ассерты :)

вот так

```cpp
Q_ASSERT(!lockFile->isNull());
Q_ASSERT(lockFile->isLocked());
```

2021-07-01 08:50 UTC, KalinaVitaly commented on src/core/management_layer/application_manager.cpp
> +        if (lockFile->isLocked()) {
Я загрузил раньше, чем ты ответил)

2021-07-01 08:50 UTC, KalinaVitaly commented on src/core/management_layer/application_manager.cpp
> +        if (lockFile->isLocked()) {
Исправлю

2021-07-02 06:30 UTC, KalinaVitaly commented on src/core/management_layer/application_manager.cpp
> +        if (lockFile->isLocked()) {
+

2021-07-02 06:30 UTC, KalinaVitaly commented on src/core/management_layer/application_manager.cpp
> +    (lockFile.data())->setStaleLockTime(0);
+

2021-07-04 04:09 UTC, merged